### ISSUE TITLE
 'OpsController' object has no attribute '_key_generator' Error

### ISSUE THREAD

**Issue by zhenglong-wu** [parkerhancock/patent_client#129]
AttributeError: 'OpsController' object has no attribute '_key_generator' when calling Inpadoc.objects.get() in version 4.1.8

Traceback (most recent call last):
  File 
...
    return Inpadoc.objects.get(number)
  File "/Users/zhenglongwu/Documents/GitHub/OxValueAI/.venv/lib/python3.10/site-packages/patent_client/util/manager.py", line 159, in get
    return run_sync(self.aget(*args, **kwargs))
  File "/Users/zhenglongwu/Documents/GitHub/OxValueAI/.venv/lib/python3.10/site-packages/patent_client/util/asyncio_util.py", line 12, in run_sync
    return loop.run_until_complete(coroutine)
  File "/Users/zhenglongwu/Documents/GitHub/OxValueAI/.venv/lib/python3.10/site-packages/nest_asyncio.py", line 99, in run_until_complete
    return f.result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/Users/zhenglongwu/Documents/GitHub/OxValueAI/.venv/lib/python3.10/site-packages/patent_client/epo/ops/published/manager.py", line 62, in aget
    result = await PublishedAsyncApi.biblio.get_biblio(number, doc_type, format)
  File "/Users/zhenglongwu/Documents/GitHub/OxValueAI/.venv/lib/python3.10/site-packages/patent_client/epo/ops/published/api.py", line 35, in get_biblio
    text = await cls.get_constituents(number, doc_type, format, constituents="biblio")
  File "/Users/zhenglongwu/Documents/GitHub/OxValueAI/.venv/lib/python3.10/site-packages/patent_client/epo/ops/published/api.py", line 30, in get_constituents
    response = await asession.get(url)
  File "/Users/zhenglongwu/Documents/GitHub/OxValueAI/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1757, in get
    return await self.request(
  File "/Users/zhenglongwu/Documents/GitHub/OxValueAI/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/Users/zhenglongwu/Documents/GitHub/OxValueAI/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "/Users/zhenglongwu/Documents/GitHub/OxValueAI/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/Users/zhenglongwu/Documents/GitHub/OxValueAI/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/Users/zhenglongwu/Documents/GitHub/OxValueAI/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/Users/zhenglongwu/Documents/GitHub/OxValueAI/.venv/lib/python3.10/site-packages/hishel/_async/_transports.py", line 97, in handle_async_request
    key = self._controller._key_generator(httpcore_request)
AttributeError: 'OpsController' object has no attribute '_key_generator'

**Comment by parkerhancock** [comment]
```
pip install --upgrade patent_client hishel
```

**Comment by zhenglong-wu** [comment]
Are you able to reproduce this error? I'm unfortunately still getting this error after upgrading package. Thanks!

**Comment by parkerhancock** [comment]
I cannot reproduce this error. Make sure you have Patent Client 4.1.8. The most recent version doesn't even make use of the key generator feature, which strongly suggests to me you're using something less than 4.1.8.

Thanks!

**Comment by echoopen** [comment]
![image](https://github.com/parkerhancock/patent_client/assets/62507651/f90c02ef-d1d5-4ff5-9310-fb7a243dcaae)

import os

os.environ['PATENT_CLIENT_EPO_API_KEY'] = "k"
os.environ['PATENT_CLIENT_EPO_SECRET'] = "yD"

from patent_client import Inpadoc
case = Inpadoc.objects.get("EP1000000A1")

same problem

**Comment by zhenglong-wu** [comment]
Tested in another environment with version 4.1.8 as well, getting same error.

**Comment by parkerhancock** [comment]
The test suite for this library is not failing and I can't reproduce the error. But I'm happy to review a well-written PR to fix this issue if you're able to identify and resolve it.

Thanks,

Parker

**Comment by zhenglong-wu** [comment]
Thanks for taking a look. I'll see if I can identify the issue.

**Comment by parkerhancock** [comment]
Also, try upgrading to 4.1.10. I added a call to `super().__init__()` that might resolve the issue. It doesn't cause problems on my end, but looking at the stack trace, might fix it on your end.

**Comment by zhenglong-wu** [comment]
Issue fixed in 4.1.9! But getting the following warning if it is of interest:

UserWarning: `convert_to_json` overrides an existing Pydantic `@model_validator` decorator
  warnings.warn(f'`{k}` overrides an existing Pydantic `{existing.decorator_info.decorator_repr}` decorator')
  
 Thanks for the update, and happy new year.
