### ISSUE TITLE
"Event Loop is closed"/Deadlocks for simultaneous requests

### ISSUE THREAD

**Issue by recurvelabs** [parkerhancock/patent_client#137]
Background:  one of the features of my app is to build patent families which requires recursively loading patents as I discover them.  To speed up loading time - if there are multiple edges that need to be explored, I explore them in parallel. 

Here is a sample stacktrace:
```
Traceback (most recent call last):
  File "/home/user/projects/app/lib/components/analysis.py", line 131, in mount
    patent = get_patent(self.patent_number)
  File "/home/user/projects/app/lib/patent.py", line 208, in get_patent
    return async_to_sync(aget_patent, force_new_loop=True)(id, fam_id)
  File "/home/user/projects/app/venv/lib/python3.10/site-packages/asgiref/sync.py", line 277, in __call__
    return call_result.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/user/projects/app/venv/lib/python3.10/site-packages/asgiref/sync.py", line 353, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/home/user/projects/app/lib//patentvuln/lib/patent.py", line 200, in aget_patent
    resp = await aquery_uspto(id, fam_id)
  File "/home/user/projects/app/lib//patentvuln/lib/patent.py", line 215, in aquery_uspto
    result = await PatentClient.objects.aget(expression)
  File "/home/user/projects/app/venv/lib/python3.10/site-packages/patent_client/util/manager.py", line 151, in aget
    length = await mger.alen()
  File "/home/user/projects/app/venv/lib/python3.10/site-packages/patent_client/uspto/public_search/manager.py", line 55, in alen
    page = await public_search_api.run_query(
  File "/home/user/projects/app/venv/lib/python3.10/site-packages/patent_client/uspto/public_search/api.py", line 75, in run_query
    query_response = await session.post(url, json=data)
  File "/home/user/projects/app/venv/lib/python3.10/site-packages/httpx/_client.py", line 1848, in post
    return await self.request(
  File "/home/user/projects/app/venv/lib/python3.10/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/user/projects/app/venv/lib/python3.10/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "/home/user/projects/app/venv/lib/python3.10/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/user/projects/app/venv/lib/python3.10/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/home/user/projects/app/venv/lib/python3.10/site-packages/httpx/_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/home/user/projects/app/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/home/user/projects/app/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 226, in handle_async_request
    await self._close_expired_connections()
  File "/home/user/projects/app/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 194, in _close_expired_connections
    await connection.aclose()
  File "/home/user/projects/app/venv/lib/python3.10/site-packages/httpcore/_async/connection.py", line 166, in aclose
    await self._connection.aclose()
  File "/home/user/projects/app/venv/lib/python3.10/site-packages/httpcore/_async/http2.py", line 424, in aclose
    await self._network_stream.aclose()
  File "/home/user/projects/app/venv/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 54, in aclose
    await self._stream.aclose()
  File "/home/user/projects/app/venv/lib/python3.10/site-packages/anyio/streams/tls.py", line 202, in aclose
    await self.transport_stream.aclose()
  File "/home/user/projects/app/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1181, in aclose
    self._transport.close()
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 706, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 753, in call_soon
    self._check_closed()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
```

Sometimes I also get this fun exception if this happens in the 'background' thread:
```
ERROR:root:Background thread failed:
Traceback (most recent call last):
  File ""/home/user/projects/app/venv/lib/python3.10/site-packages/anyio/streams/tls.py", line 140, in _call_sslobject_method
    result = func(*args)
  File "/usr/lib/python3.10/ssl.py", line 917, in read
    v = self._sslobj.read(len)
ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2578)

During handling of the above exception, another exception occurred:
...similar stacktrace as above
```

I'm using python 3.11 and patent client 4.1.2 (I upgraded python to make sure it wasn't one of the existing known async issues).

Once we get to this state nothing loads and the app needs to be restarted.   Annoyingly this is intermittent so it's hard to reproduce. 
 The only thing I can think of is we're sometimes calling patent_client from different threads (different web workers) so something may not be thread-safe.      I imagine the problem is in the lower levels of python/httpx but I thought I'd mention it here in case you had any ideas.

TODO for me is to try and get a script that reliably reproduces this.

**Comment by parkerhancock** [comment]
Hi @recurvelabs!

Yes, this is a known issue. I'm tracking progress towards the solution at #133.

Thanks!

Parker

**Comment by recurvelabs** [comment]
FWIW as a possible workaround I've seem to have had some success with:

```
_loop = asyncio.new_event_loop()

def start_background_loop(loop: asyncio.AbstractEventLoop) -> None:
    asyncio.set_event_loop(loop)
    loop.run_forever()

t = threading.Thread(target=start_background_loop, args=(_loop,), daemon=True)
t.start()
```

And then when I need to call patent_client I use `asyncio.run_coroutine_threadsafe(aget_patent(id), _loop)`.

**Comment by davidtingsu** [comment]
If we just use the `async/await` for a single object, @parkerhancock, would we still expect to see issues with simultaneous requests?
is there reusable code that we could use just to make a singular request for a patent that is thread safe?
I have something like the following code :
```python
async def get_patent(patent_number):
  return await Patent.objects.aget(patent_number)
```

**Comment by parkerhancock** [comment]
This should be fixed in v5, which I just released. I more clearly segregated the async/sync versions of the library, so you now pick one or other other, and then stick with it. Should fix this and all related issues!
