### ISSUE TITLE
Error while using example functions

### ISSUE THREAD

**Issue by VolkovIlia** [parkerhancock/patent_client#73]
```python
from patent_client import Inpadoc, Assignment, USApplication, Patent
results = Inpadoc.objects.filter(cql_query='pa="Google LLC"')
len(results) > 100
```

error
```python
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 960, in json
    return complexjson.loads(self.content.decode(encoding), **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/volk/patents_search/test.py", line 21, in <module>
    print(len(results) > 100)
  File "/home/volk/.local/lib/python3.10/site-packages/patent_client/epo/ops/published/manager.
py", line 19, in __len__
    page = self._get_search_results_range(1, 100)
  File "/home/volk/.local/lib/python3.10/site-packages/patent_client/epo/ops/published/manager.
py", line 16, in _get_search_results_range
    return PublishedApi.search.search(query, start, end)
  File "/home/volk/.local/lib/python3.10/site-packages/patent_client/epo/ops/published/api.py",
 line 104, in search
    response = session.get(base_url, params={"Range": range, "q": query})
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/home/volk/.local/lib/python3.10/site-packages/patent_client/epo/ops/session.py", line
24, in request
    auth_response = self.get_token()
  File "/home/volk/.local/lib/python3.10/site-packages/patent_client/epo/ops/session.py", line
37, in get_token
    data = response.json()
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 968, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

shell returned 1

```

Example
```python
from patent_client import USApplication
apps = (USApplication.objects
        # Step 1 - Query the Data
        .filter(first_named_applicant="Google")
        .order_by("-appl_filing_date")
        .limit(20)
        # Step 2 - Reshape the Data
        .values("appl_id", "app_filing_date", "patent_title", "patent_number", "issue_date", "inventors.0.name")
        # Step 3 - Process the data
        .to_pandas()
        .assign(time_to_issue=lambda df: df.issue_date - df.app_filing_date)
        .mean()
        .time_to_issue
        )
```

Error

```python
 File "/home/volk/.local/lib/python3.10/site-packages/patent_client/util/base/manager.py", lin
e 60, in __iter__
    for item in self._get_results():
  File "/home/volk/.local/lib/python3.10/site-packages/patent_client/uspto/peds/manager.py", li
ne 51, in _get_results
    num_pages = math.ceil(len(self) / self.page_size)
  File "/home/volk/.local/lib/python3.10/site-packages/patent_client/uspto/peds/manager.py", li
ne 43, in __len__
    max_length = self.get_page(0)["numFound"] - self.config.offset
  File "/home/volk/.local/lib/python3.10/site-packages/patent_client/uspto/peds/manager.py", li
ne 71, in get_page
    raise HttpException(
patent_client.uspto.peds.manager.HttpException: 404
<!doctype html><html lang="en"><head><title>HTTP Status 404 ? Not Found</title><style type="tex
t/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:
#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a
{color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1
>HTTP Status 404 ? Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Messa
ge</b> The requested resource [&#47;api&#47;error&#47;error] is not available</p><p><b>Descript
ion</b> The origin server did not find a current representation for the target resource or is n
ot willing to disclose that one exists.</p><hr class="line" /><h3>Apache Tomcat/9.0.62</h3></bo
dy></html>
{'Content-Type': 'text/html;charset=ISO-8859-1', 'Content-Length': '770', 'Connection': 'keep-a
live', 'Date': 'Wed, 02 Nov 2022 15:18:26 GMT', 'Server-Timing': 'intid;desc=142a3b6ca7f7147b',
 'Strict-Transport-Security': 'max-age=31536000;includeSubDomains', 'X-Frame-Options': 'DENY',
'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-
cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'Content-La
nguage': 'en', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 07d5d44815808d5d5a6f43984a987698
.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'OSL50-P1', 'X-Amz-Cf-Id': 'vyCVnH5adlizgEws5EXy
WWVqj42cubLE1t6XLWvFheWSedSv9p3u0A=='}
{"qf": "appEarlyPubNumber applId appLocation appType appStatus_txt appConfrNumber appCustNumber
 appGrpArtNumber appCls appSubCls appEntityStatus_txt patentNumber patentTitle primaryInventor
firstNamedApplicant appExamName appExamPrefrdName appAttrDockNumber appPCTNumber appIntlPubNumb
er wipoEarlyPubNumber pctAppType firstInventorFile appClsSubCls rankAndInventorsList", "fl": "*
", "fq": [], "searchText": "firstNamedApplicant:(Google)", "sort": "applFilingDate desc", "face
t": "false", "mm": "100%", "start": 0}
```

**Comment by parkerhancock** [comment]
Closed as duplicate of #74
