### ISSUE TITLE
demonstration code does not work

### ISSUE THREAD

**Issue by drmatthewclark** [parkerhancock/patent_client#78]
on the web page https://pypi.org/project/patent-client/.    the quick start example:

 Import the model classes you need
>>> from patent_client import Inpadoc, Assignment, USApplication, Patent

 Fetch US Patents with the word "tennis" in their title issued in 2010
>>> pats = Patent.objects.filter(title="tennis", issue_date="2010-01-01->2010-12-31")
>>> len(pats) > 10
True

When I execute this I get:

>>> pats = Patent.objects.filter(title="tennis", issue_date="2010-01-01->2010-12-31")
>>> len(pats)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mclark/.local/lib/python3.10/site-packages/patent_client/uspto/fulltext/manager.py", line 61, in __len__
    self.get_page(0)
  File "/home/mclark/.local/lib/python3.10/site-packages/patent_client/uspto/fulltext/manager.py", line 153, in get_page
    results = self.parse_page(response_text)
  File "/home/mclark/.local/lib/python3.10/site-packages/patent_client/uspto/fulltext/manager.py", line 169, in parse_page
    result = self.__schema__.load(tree)
  File "/home/mclark/.local/lib/python3.10/site-packages/yankee/base/deserializer.py", line 106, in load
    return self.post_load(loaded_obj)
  File "/home/mclark/.local/lib/python3.10/site-packages/patent_client/util/schema_mixin.py", line 27, in post_load
    return self.__model__(**obj)
TypeError: Patent.__init__() missing 1 required positional argument: 'publication_number'
>>> len(pats) > 10
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mclark/.local/lib/python3.10/site-packages/patent_client/uspto/fulltext/manager.py", line 61, in __len__
    self.get_page(0)
  File "/home/mclark/.local/lib/python3.10/site-packages/patent_client/uspto/fulltext/manager.py", line 153, in get_page
    results = self.parse_page(response_text)
  File "/home/mclark/.local/lib/python3.10/site-packages/patent_client/uspto/fulltext/manager.py", line 169, in parse_page
    result = self.__schema__.load(tree)
  File "/home/mclark/.local/lib/python3.10/site-packages/yankee/base/deserializer.py", line 106, in load
    return self.post_load(loaded_obj)
  File "/home/mclark/.local/lib/python3.10/site-packages/patent_client/util/schema_mixin.py", line 27, in post_load
    return self.__model__(**obj)
TypeError: Patent.__init__() missing 1 required positional argument: 'publication_number'

"

**Comment by parkerhancock** [comment]
The Patents and PublishedApplication endpoints were supported by the PatFT/AppFT databases which were deprecated by the USPTO at the end of October. We are working on an update supported by Patents Public Search, which is being tracked under #63 

I'll add a note to the documentation when I can about that deprecation.
