### ISSUE TITLE
issue with running the demonstration code

### ISSUE THREAD

**Issue by ravitd10** [parkerhancock/patent_client#85]
Hello, 

First, thank you for building API. 

Second, I was testing the following demonstration code and its giving me a weird error. I believe the error occurs when the patent_client module tries to interact with the European Patent Office's (EPO) Open Patent Services (OPS) API.

Demonstration code:
```
from patent_client import USApplication

google_apps = USApplication.objects.filter(first_named_applicant='Google LLC')

print(len(google_apps) > 1000)
```

Error:

`File "C:\Users\ravit\PycharmProjects\patentApplication\simple_patent_app_retriever.py", line 1, in <module>
    from patent_client import USApplication
  File "C:\Users\ravit\AppData\Local\Programs\Python\Python39\lib\site-packages\patent_client\__init__.py", line 44, in <module>
    from patent_client.epo.ops.published.model import Inpadoc  # isort:skip
  File "C:\Users\ravit\AppData\Local\Programs\Python\Python39\lib\site-packages\patent_client\epo\ops\__init__.py", line 2, in <module>
    from .legal.model import Legal
  File "C:\Users\ravit\AppData\Local\Programs\Python\Python39\lib\site-packages\patent_client\epo\ops\legal\__init__.py", line 3, in <module>
    generate_legal_code_db()
  File "C:\Users\ravit\AppData\Local\Programs\Python\Python39\lib\site-packages\patent_client\epo\ops\legal\national_codes.py", line 30, in generate_legal_code_db
    path = get_spreadsheet()
  File "C:\Users\ravit\AppData\Local\Programs\Python\Python39\lib\site-packages\patent_client\epo\ops\legal\national_codes.py", line 50, in get_spreadsheet
    response = session.get(url)
  File "C:\Users\ravit\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\ravit\AppData\Local\Programs\Python\Python39\lib\site-packages\patent_client\epo\ops\session.py", line 22, in request
    response = super(OpsSession, self).request(*args, **kwargs)
  File "C:\Users\ravit\AppData\Local\Programs\Python\Python39\lib\site-packages\requests_cache\session.py", line 115, in request
    return super().request(method, url, *args, **kwargs)
  File "C:\Users\ravit\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\ravit\AppData\Local\Programs\Python\Python39\lib\site-packages\requests_cache\session.py", line 147, in send
    response = self._send_and_cache(request, actions, **kwargs)
  File "C:\Users\ravit\AppData\Local\Programs\Python\Python39\lib\site-packages\requests_cache\session.py", line 193, in _send_and_cache
    self.cache.save_response(response, actions.cache_key, actions.expires)
  File "C:\Users\ravit\AppData\Local\Programs\Python\Python39\lib\site-packages\requests_cache\policy\actions.py", line 112, in expires
    return get_expiration_datetime(self.expire_after)
  File "C:\Users\ravit\AppData\Local\Programs\Python\Python39\lib\site-packages\requests_cache\policy\actions.py", line 170, in get_expiration_datetime
    raise ValueError(f'Invalid HTTP date: {expire_after}')
ValueError: Invalid HTTP date: 3 days`

**Comment by parkerhancock** [comment]
I'm investigating this. It looks like the issue is a feature rollback in `requests_cache`. 

Thanks for notifying me of the issue!

**Comment by parkerhancock** [comment]
I believe this issue is solved in v.3.0.6. Please update and let me know if you are still having issues.

**Comment by ravitd10** [comment]
Hi Parker, thanks for filing this instant issue. However, I am now getting the following error when I try to run `app = USApplication.objects.get('15710770')`

`Traceback (most recent call last):
  File "C:\Users\ravit\PycharmProjects\patentApplication\simple_patent_app_retriever.py", line 1, in <module>
    from patent_client import USApplication
  File "C:\Users\ravit\AppData\Local\Programs\Python\Python39\lib\site-packages\patent_client\__init__.py", line 41, in <module>
    session = PatentClientSession()
  File "C:\Users\ravit\AppData\Local\Programs\Python\Python39\lib\site-packages\patent_client\session.py", line 15, in __init__
    expire_after=datetime.timedelta(days=SETTINGS.CACHE.MAX_AGE),
TypeError: unsupported type for timedelta days component: str`
